# Generated by Django 5.2 on 2025-05-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='magic_login_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='magic_login_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
